<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Default suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Default test(failed)">
    <classes>
      <class name="S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest">
        <methods>
          <include name="whileSignIntoApplicationGivenRightReferralCodePassedTest"/>
          <include name="whileSignIntoApplicationGivenWrongReferralCodeErrorTest"/>
          <include name="whileSignIntoApplicationSkipHeardAboutUsDropDwnValueErrorTest"/>
          <include name="whileSignIntoApplicationExistingPhoneNumberGivenErrorTest"/>
          <include name="whileSignIntoApplicationSkipNameErrorTest"/>
          <include name="whileSignIntoApplicationPhoneNumberNotGivenErrorTest"/>
          <include name="whileSignIntoApplicationEnterMoreThan10NumbersInMobileNumTextFieldErrorTest"/>
          <include name="whileSignIntoApplicationExistingEmailGivenErrorTest"/>
        </methods>
      </class> <!-- S2_Negative_Scenarious_for_SignupLoginSchemesDepositAmountSprint_1_Stg.Done_SignUpModuleNegativeScenarios_StgTest -->
    </classes>
  </test> <!-- Default test(failed) -->
</suite> <!-- Failed suite [Default suite] -->
